const lorem =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

const dailyDetails =
  "Daily Details is my personal daily planner and motivaional tool. The concept is to order your day in terms of importance, taking the decision making out of scheduling. By changing the most important parts of your day from a task that takes brain power and limited decision making into something that is done without thought, like eating, or washing your hands, you save brain power and motivation for more tasks. Using this tool I consistently went to the gym 5 days a week for 6 consecuative months. Interupted only by quarantine. I continue to use this every morning to plan out my day. Created in plain javascript, css, and html on the client side. Using Node.js and express and the sever side";

const OMPdesc =
  "One Million Pounds (OMP) is a react native moble app currently on the google play store with a whopping six downloads. It is a weight lifting fitness tracker with the built in goal of lifting one million pounds (cumulatively) in a short a time frame as possible. After doing some estimates and napkin math, I set out to lift the cumulative one million pounds in 90 days. Using the OMP app in conjunction with my daily planner dailyDetails, I hit 1,000,175 pounds on the 89th day.";

const quizMeDesc =
  "A website so that anyone can create buzzfeed style quizzes easily! Front-end develpment done in React.js. Back-end done in Rust by Shane Murphy";

const hatDesc =
  "My graduation cap decked out with a servo motor, a 9 volt battery, a bread board with regulator, a 6X8 LED matrix, and a start button. Basic electronics and embedded programming used, but not shown because my robotics skills are nothing to brag about";

const teaDesc =
  "Tea making robot! Actually used for about a week with moderate success.";

export { lorem, dailyDetails, OMPdesc, quizMeDesc, hatDesc, teaDesc };
